id: P006846
initial_creation_type: ocr
source_metadata:
  id: bdr:W29041
  title: སྡེ་དགེ་དགོན་ཆེན་དགོན་པའི་ལོ་རྒྱུས
  author: ''
  volumes:
    905eba7e0a224085853686204b3c3bfd:
      image_group_id: I00KG03699
      title: ''
      volume_number: 1
      total_pages: 191
      base_file: v001.txt
