id: P006846
initial_creation_type: ocr
created_at: 26/03/2020
last_modified_at: 2021-12-17 12:26:19.753698
source_metadata:
  id: bdr:W29041
  title: སྡེ་དགེ་དགོན་ཆེན་དགོན་པའི་ལོ་རྒྱུས
  author: ''
  volumes:
    905eba7e0a224085853686204b3c3bfd:
      image_group_id: I00KG03699
      title: ''
      volume_number: 1
      total_pages: 191
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
